# GNU Make solution makefile autogenerated by Premake
# Type "make help" for usage help

ifndef config
  config=debug
endif
export config

PROJECTS := Tester

.PHONY: all clean help $(PROJECTS)

all: $(PROJECTS)

Tester: 
	@echo "==== Building Tester ($(config)) ===="
	@${MAKE} --no-print-directory -C . -f Tester.make

clean:
	@${MAKE} --no-print-directory -C . -f Tester.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "   debug"
	@echo "   release"
	@echo "   cluster"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Tester"
	@echo ""
	@echo "For more information, see http://industriousone.com/premake/quick-start"
